version: "3.8"
services:
  # password: Passw0rd
  # user: sa
  # database: master
  mssql:
    image: bb/mssql
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - "1433:1433"
